#!/bin/bash

defaultoption=syntax
option=${1-$defaultoption}

beforecommit=master # TODO this should be MOODLE_27_STABLE if need be
aftercommit=HEAD

files="$(git diff $beforecommit $aftercommit --name-only)"

if [ "$option" = "syntax" -o "$option" = "all" ]; then

    for modified_file in ${files}; do
        after=${after}"\n==\n(After) File: $modified_file\n==\n"
        after=$after"$(php local/codechecker/run.php $modified_file)"
        # TODO moodlecheck
    done;

    stash="$(git stash)"

    git checkout ${beforecommit}

    for modified_file in ${files}; do
        before=${before}"\n==\n(Before) File: $modified_file\n==\n"
        before=$before"$(php local/codechecker/run.php $modified_file)"
        # TODO moodlecheck
    done;

    git checkout ${aftercommit}

    if [ ! "$stash" = "No local changes to save" ]; then
        git stash pop > /dev/null
    fi

    diff -y <(printf "${before}") <(printf "${after}")

fi

if [ "$option" = "test" -o "$option" = "all" ]; then

    paths=""

    for modified_file in ${files}; do

        currentPath=$modified_file

        while [ ! -d "$testDir" -a -n "$currentPath" ]; do

            if [ -n "$currentPath" ]; then
                tryDir="$currentPath"tests/

                if [ -d "$tryDir" ]; then
                    testDir=$tryDir
                fi
            fi

            currentPath="${currentPath%?}"
            currentPath="$(echo $currentPath | grep -oh '^.*/')"

        done

        paths="$paths"$'\n'"$testDir"
        testDir=""

    done;

    # sort | uniq

    if [ -n "$paths" ]; then

        paths=$(sort <(printf "$paths"))
        paths=$(uniq <(printf "$paths"))

        for testDir in ${paths}; do

            if [ -d "$testDir" ]; then
                tests="$(ls -1d $testDir* | grep _test\.php)"

                while read -r test; do
                    commands=$commands"mdk phpunit -r -u "$test$'\n'
                done <<< "$tests"
            fi

            if [ -d "$testDir"/behat ]; then
                tests="$(ls -1d ${testDir}behat/*)"

                while read -r test; do
                    commands=$commands"mdk phpunit -r -u "$test$'\n'
                done <<< "$tests"
            fi

        done;

        if [ "$2" = "-r" ]; then

            commands="${commands%?}"

            while read -r command; do
                printf $'\n==\n'"running $command"$'\n==\n'
                eval $command
            done <<< "$commands"

        else

            printf "${commands}"

        fi

    fi

fi
